export const SETAR_ALBUMS = 'SETAR_ALBUMS';
export const ADICIONAR_ALBUMS = 'ADICIONAR_ALBUMS';
export const SETAR_ARTISTAS = 'SETAR_ARTISTAS';
export const ADICIONAR_ARTISTAS = 'ADICIONAR_ARTISTAS';
export const SETAR_PLAYLIST = 'SETAR_PLAYLIST';
export const ADICIONAR_PLAYLIST = 'ADICIONAR_PLAYLIST';
